{{- if .Values.redis.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "atlantis.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atlantis.labels" . | nindent 4 }}
  {{- with .Values.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
stringData:
  password: {{ .Values.redis.password }}
{{- end }}
