{{- if not .Values.vcsSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "atlantis.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atlantis.labels" . | nindent 4 }}
  {{- with .Values.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
stringData:
  {{- if .Values.githubApp }}
  key.pem: {{ required "githubApp.key is required if githubApp configuration is specified." .Values.githubApp.key }}
  github_secret: {{ required "githubApp.secret is required if githubApp configuration is specified." .Values.githubApp.secret }}
  {{- end }}
  {{- if .Values.github.user }}
  github_token: {{ required "github.token is required if github configuration is specified." .Values.github.token }}
  github_secret: {{ required "github.secret is required if github configuration is specified." .Values.github.secret }}
  {{- end }}
  {{- if .Values.gitea }}
  gitea_token: {{ required "gitea.token is required if gitea configuration is specified." .Values.gitea.token }}
  gitea_secret: {{ required "gitea.secret is required if gitea configuration is specified." .Values.gitea.secret }}
  {{- end }}
  {{- if .Values.gitlab }}
  gitlab_token: {{ required "gitlab.token is required if gitlab configuration is specified." .Values.gitlab.token }}
  gitlab_secret: {{ required "gitlab.secret is required if gitlab configuration is specified." .Values.gitlab.secret }}
  {{- end }}
  {{- if .Values.bitbucket }}
  bitbucket_token: {{ required "bitbucket.token is required if bitbucket configuration is specified." .Values.bitbucket.token }}
  {{- if .Values.bitbucket.baseURL }}
  bitbucket_secret: {{ required "bitbucket.secret is required if bitbucket.baseURL is specified." .Values.bitbucket.secret }}
  {{- end }}
  {{- end }}
  {{- if .Values.azuredevops }}
  azuredevops_token: {{ required "azuredevops.token is required if azuredevops configuration is specified." .Values.azuredevops.token }}
  azuredevops_webhook_password: {{ required "azuredevops.webhookPassword is required if azuredevops configuration is specified." .Values.azuredevops.webhookPassword }}
  {{- end }}
{{- end }}
