{{- if or .Values.aws.credentials .Values.aws.config }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "atlantis.fullname" . }}-aws
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atlantis.labels" . | nindent 4 }}
  {{- with .Values.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
stringData:
  {{- if .Values.aws.credentials }}
  credentials: {{ .Values.aws.credentials }}
  {{- end }}
  {{- if .Values.aws.config }}
  config: {{ .Values.aws.config }}
  {{- end }}
{{- end }}
